name:                 a4
version:              0.1.0.0
visibility:           public
id:                   a4-0.1.0.0-inplace
key:                  a4-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      CharMap Huffman PriorityQueue
import-dirs:
    /home/nasir/stuff/projects/4fp3/a4-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a4-0.1.0.0/build

library-dirs:
    /home/nasir/stuff/projects/4fp3/a4-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a4-0.1.0.0/build

library-dirs-static:
    /home/nasir/stuff/projects/4fp3/a4-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a4-0.1.0.0/build

dynamic-library-dirs:
    /home/nasir/stuff/projects/4fp3/a4-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a4-0.1.0.0/build

data-dir:             /home/nasir/stuff/projects/4fp3/a4-template/.
hs-libraries:         HSa4-0.1.0.0-inplace
depends:
    base-4.19.2.0-0fde
    containers-0.8-1b1a7aa3d2295a8626e2da7d3bfd8454ababdc50b7cda43f5f5abd41079b7782

haddock-interfaces:
    /home/nasir/stuff/projects/4fp3/a4-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a4-0.1.0.0/doc/html/a4/a4.haddock

haddock-html:
    /home/nasir/stuff/projects/4fp3/a4-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a4-0.1.0.0/doc/html/a4
