cabal-version:      3.0
name:               a1
version:            0.1.0.0
license:            NONE
build-type:         Simple

common ghc-options
    ghc-options: -Wall -fdefer-typed-holes

library
    import: ghc-options
    exposed-modules:
        A1.Automatic
        A1.Numeric
        A1.Polynomial
        A1.Symbolic
        A1.B1
        A1.B2
        A1.B3
    build-depends:
        base ^>=4.19.2.0
    hs-source-dirs: src
    default-language: Haskell2010

test-suite solution-test
    import: ghc-options
    default-language: Haskell2010
    type: exitcode-stdio-1.0
    hs-source-dirs: test
    main-is: Main.hs
    build-depends:
        base ^>=4.19.2.0,
        tasty >= 1.5,
        tasty-hunit >= 0.10,
        a1
