name:                 a2
version:              0.1.0.0
visibility:           public
id:                   a2-0.1.0.0-inplace
key:                  a2-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      A2.Board A2.Bot A2.Game A2.Grid4x4 A2.Quadruple
import-dirs:
    /home/nasir/stuff/projects/school/4fp3/A2_khimanin/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a2-0.1.0.0/build

library-dirs:
    /home/nasir/stuff/projects/school/4fp3/A2_khimanin/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a2-0.1.0.0/build

library-dirs-static:
    /home/nasir/stuff/projects/school/4fp3/A2_khimanin/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a2-0.1.0.0/build

dynamic-library-dirs:
    /home/nasir/stuff/projects/school/4fp3/A2_khimanin/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a2-0.1.0.0/build

data-dir:             /home/nasir/stuff/projects/school/4fp3/A2_khimanin/.
hs-libraries:         HSa2-0.1.0.0-inplace
depends:
    base-4.19.2.0-0fde mtl-2.3.1-5e32
    random-1.3.1-1440f03c64e586d984eb5f40c884ef492310230022e338d5c06d8b514fd52800

haddock-interfaces:
    /home/nasir/stuff/projects/school/4fp3/A2_khimanin/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a2-0.1.0.0/doc/html/a2/a2.haddock

haddock-html:
    /home/nasir/stuff/projects/school/4fp3/A2_khimanin/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a2-0.1.0.0/doc/html/a2
