name:                 a1
version:              0.1.0.0
visibility:           public
id:                   a1-0.1.0.0-inplace
key:                  a1-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      A1.Automatic A1.Numeric A1.Polynomial A1.Symbolic
import-dirs:
    /home/nasir/stuff/projects/school/4fp3/a1-skeleton/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a1-0.1.0.0/build

library-dirs:
    /home/nasir/stuff/projects/school/4fp3/a1-skeleton/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a1-0.1.0.0/build

library-dirs-static:
    /home/nasir/stuff/projects/school/4fp3/a1-skeleton/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a1-0.1.0.0/build

dynamic-library-dirs:
    /home/nasir/stuff/projects/school/4fp3/a1-skeleton/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a1-0.1.0.0/build

data-dir:             /home/nasir/stuff/projects/school/4fp3/a1-skeleton/.
hs-libraries:         HSa1-0.1.0.0-inplace
depends:              base-4.19.2.0-0fde
haddock-interfaces:
    /home/nasir/stuff/projects/school/4fp3/a1-skeleton/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a1-0.1.0.0/doc/html/a1/a1.haddock

haddock-html:
    /home/nasir/stuff/projects/school/4fp3/a1-skeleton/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a1-0.1.0.0/doc/html/a1
