name:                 a5
version:              0.1.0.0
visibility:           public
id:                   a5-0.1.0.0-inplace
key:                  a5-0.1.0.0-inplace
maintainer:           mullanir@mcmaster.ca
author:               Reed Mullanix
abi:                  inplace
exposed:              True
exposed-modules:
    A5.Compile A5.Data.Array.Pure A5.Eval.Partial A5.Eval.Pure
    A5.Language A5.Language.Notation A5.Language.Ring A5.Poly.Sparse

import-dirs:
    /home/nasir/stuff/projects/school/4fp3/a5/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a5-0.1.0.0/build

library-dirs:
    /home/nasir/stuff/projects/school/4fp3/a5/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a5-0.1.0.0/build

library-dirs-static:
    /home/nasir/stuff/projects/school/4fp3/a5/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a5-0.1.0.0/build

dynamic-library-dirs:
    /home/nasir/stuff/projects/school/4fp3/a5/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a5-0.1.0.0/build

data-dir:             /home/nasir/stuff/projects/school/4fp3/a5/.
hs-libraries:         HSa5-0.1.0.0-inplace
depends:
    base-4.19.2.0-0fde
    containers-0.8-1b1a7aa3d2295a8626e2da7d3bfd8454ababdc50b7cda43f5f5abd41079b7782
    vector-0.13.2.0-942b48feccda76d7fe982ae9186a780f15f69d6a64fca0ecffbe37d15eeccc6f

haddock-interfaces:
    /home/nasir/stuff/projects/school/4fp3/a5/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a5-0.1.0.0/doc/html/a5/a5.haddock

haddock-html:
    /home/nasir/stuff/projects/school/4fp3/a5/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a5-0.1.0.0/doc/html/a5
