name:                 a6
version:              0.1.0.0
visibility:           public
id:                   a6-0.1.0.0-inplace
key:                  a6-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            2026 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/a6#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/a6#readme>

abi:                  inplace
exposed:              True
exposed-modules:      A6.CataAna A6.Fix A6.Para A6.Poly A6.RegExp
import-dirs:
    /home/nasir/stuff/projects/school/4fp3/a6-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a6-0.1.0.0/build

library-dirs:
    /home/nasir/stuff/projects/school/4fp3/a6-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a6-0.1.0.0/build

library-dirs-static:
    /home/nasir/stuff/projects/school/4fp3/a6-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a6-0.1.0.0/build

dynamic-library-dirs:
    /home/nasir/stuff/projects/school/4fp3/a6-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a6-0.1.0.0/build

data-dir:             /home/nasir/stuff/projects/school/4fp3/a6-template/.
hs-libraries:         HSa6-0.1.0.0-inplace
depends:              base-4.19.2.0-0fde containers-0.6.8-ddec
haddock-interfaces:
    /home/nasir/stuff/projects/school/4fp3/a6-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a6-0.1.0.0/doc/html/a6/a6.haddock

haddock-html:
    /home/nasir/stuff/projects/school/4fp3/a6-template/dist-newstyle/build/x86_64-linux/ghc-9.8.4/a6-0.1.0.0/doc/html/a6
