name:                 T01
version:              0.1.0.0
visibility:           public
id:                   T01-0.1.0.0-inplace
key:                  T01-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           CS4FP3
author:               CS4FP3
abi:                  inplace
exposed:              True
exposed-modules:      T01
import-dirs:
    /home/nasir/stuff/projects/school/4fp3/T01/dist-newstyle/build/x86_64-linux/ghc-9.8.4/T01-0.1.0.0/build

library-dirs:
    /home/nasir/stuff/projects/school/4fp3/T01/dist-newstyle/build/x86_64-linux/ghc-9.8.4/T01-0.1.0.0/build

library-dirs-static:
    /home/nasir/stuff/projects/school/4fp3/T01/dist-newstyle/build/x86_64-linux/ghc-9.8.4/T01-0.1.0.0/build

dynamic-library-dirs:
    /home/nasir/stuff/projects/school/4fp3/T01/dist-newstyle/build/x86_64-linux/ghc-9.8.4/T01-0.1.0.0/build

data-dir:             /home/nasir/stuff/projects/school/4fp3/T01/.
hs-libraries:         HST01-0.1.0.0-inplace
depends:              base-4.19.2.0-0fde
haddock-interfaces:
    /home/nasir/stuff/projects/school/4fp3/T01/dist-newstyle/build/x86_64-linux/ghc-9.8.4/T01-0.1.0.0/doc/html/T01/T01.haddock

haddock-html:
    /home/nasir/stuff/projects/school/4fp3/T01/dist-newstyle/build/x86_64-linux/ghc-9.8.4/T01-0.1.0.0/doc/html/T01
